
export const DURATION_RANGE_ALL = "Any Duration";
export const DURATION_RANGE_UNDER_30 = "Under 30 min";
export const DURATION_RANGE_30_TO_60 = "30–60 min";
export const DURATION_RANGE_60_TO_90 = "60–90 min";
export const DURATION_RANGE_OVER_90 = "Over 90 min";

export const DURATION_RANGE_OPTIONS = [
  DURATION_RANGE_ALL,
  DURATION_RANGE_UNDER_30,
  DURATION_RANGE_30_TO_60,
  DURATION_RANGE_60_TO_90,
  DURATION_RANGE_OVER_90,
];
