
const NOTIFICATION_CATEGORIES = {
  PROGRESS: "progress",
  CARDIO: "cardio",
  REMINDERS: "reminders",
  INSIGHTS: "insights",
};

const NOTIFICATION_TYPES = {
  PERSONAL_RECORD: "personalRecord",
  GOAL_COMPLETED: "goalCompleted",
  GOAL_THRESHOLD: "goalThreshold",
  STREAK_MILESTONE: "streakMilestone",
  LONGEST_WORKOUT: "longestWorkout",
  HIGHEST_VOLUME: "highestVolume",
  NEW_LONGEST_RUN: "newLongestRun",
  WEEKLY_VOLUME_INCREASED: "weeklyVolumeIncreased",
  MUSCLE_GROUP_NEGLECTED: "muscleGroupNeglected",
  WORKOUT_SCHEDULED: "workoutScheduled",
  WORKOUT_RESCHEDULED: "workoutRescheduled",
  RECURRING_SCHEDULE_CREATED: "recurringScheduleCreated",
  WORKOUT_CANCELLED: "workoutCancelled",

  WORKOUT_TODAY: "workoutToday",
  WORKOUT_STARTING_SOON: "workoutStartingSoon",
  WORKOUT_OVERDUE: "workoutOverdue",
  WORKOUT_MISSED_YESTERDAY: "workoutMissedYesterday",
  RECURRING_DUE_TOMORROW: "recurringDueTomorrow",
  GOAL_PROGRESS_REMINDER: "goalProgressReminder",
  GOAL_EXPIRING_TODAY: "goalExpiringToday",
  MILESTONE_ALMOST_COMPLETE: "milestoneAlmostComplete",
  STREAK_PROTECTION: "streakProtection",
  CARDIO_STREAK_EXPIRING: "cardioStreakExpiring",
  CARDIO_SESSION_DUE: "cardioSessionDue",
  CARDIO_ACTIVITY_NOT_LOGGED: "cardioActivityNotLogged",
  PLANNER_RESCHEDULE_WARNING: "plannerRescheduleWarning",
  PLANNER_OVERLAP: "plannerOverlap",
  PLANNER_SERIES_ENDING_SOON: "plannerSeriesEndingSoon",
  FIRST_WORKOUT_AFTER_BREAK: "firstWorkoutAfterBreak",

  PLATEAU_DETECTED: "plateauDetected",
  WEEKLY_GRADE_IMPROVED: "weeklyGradeImproved",
  VOLUME_LANDMARK_ACHIEVED: "volumeLandmarkAchieved",

  NEW_FOLLOWER: "newFollower",
  BADGE_EARNED: "badgeEarned",
  NEW_MESSAGE: "newMessage",
  PHYSIQUE_LIKED: "physiqueLiked",
  PHYSIQUE_COMMENTED: "physiqueCommented",
  PHYSIQUE_REACTED: "physiqueReacted",
};

const TYPE_PRIORITY = {
  [NOTIFICATION_TYPES.WORKOUT_OVERDUE]: "critical",
  [NOTIFICATION_TYPES.STREAK_PROTECTION]: "critical",
  [NOTIFICATION_TYPES.CARDIO_STREAK_EXPIRING]: "critical",
  [NOTIFICATION_TYPES.GOAL_EXPIRING_TODAY]: "critical",

  [NOTIFICATION_TYPES.WORKOUT_TODAY]: "high",
  [NOTIFICATION_TYPES.WORKOUT_STARTING_SOON]: "high",
  [NOTIFICATION_TYPES.WORKOUT_MISSED_YESTERDAY]: "high",
  [NOTIFICATION_TYPES.PLANNER_OVERLAP]: "high",

  [NOTIFICATION_TYPES.GOAL_PROGRESS_REMINDER]: "medium",
  [NOTIFICATION_TYPES.GOAL_THRESHOLD]: "medium",
  [NOTIFICATION_TYPES.CARDIO_SESSION_DUE]: "medium",
  [NOTIFICATION_TYPES.CARDIO_ACTIVITY_NOT_LOGGED]: "medium",
  [NOTIFICATION_TYPES.RECURRING_DUE_TOMORROW]: "medium",
  [NOTIFICATION_TYPES.PLANNER_RESCHEDULE_WARNING]: "medium",
  [NOTIFICATION_TYPES.PLANNER_SERIES_ENDING_SOON]: "medium",
  [NOTIFICATION_TYPES.MILESTONE_ALMOST_COMPLETE]: "medium",

  [NOTIFICATION_TYPES.PERSONAL_RECORD]: "low",
  [NOTIFICATION_TYPES.GOAL_COMPLETED]: "low",
  [NOTIFICATION_TYPES.STREAK_MILESTONE]: "low",
  [NOTIFICATION_TYPES.HIGHEST_VOLUME]: "low",
  [NOTIFICATION_TYPES.LONGEST_WORKOUT]: "low",
  [NOTIFICATION_TYPES.NEW_LONGEST_RUN]: "low",
  [NOTIFICATION_TYPES.WEEKLY_VOLUME_INCREASED]: "low",
  [NOTIFICATION_TYPES.FIRST_WORKOUT_AFTER_BREAK]: "low",
  [NOTIFICATION_TYPES.WORKOUT_SCHEDULED]: "low",
  [NOTIFICATION_TYPES.WORKOUT_RESCHEDULED]: "low",
  [NOTIFICATION_TYPES.RECURRING_SCHEDULE_CREATED]: "low",
  [NOTIFICATION_TYPES.WORKOUT_CANCELLED]: "low",

  [NOTIFICATION_TYPES.PLATEAU_DETECTED]: "medium",
  [NOTIFICATION_TYPES.WEEKLY_GRADE_IMPROVED]: "low",
  [NOTIFICATION_TYPES.VOLUME_LANDMARK_ACHIEVED]: "low",

  [NOTIFICATION_TYPES.NEW_FOLLOWER]: "low",
  [NOTIFICATION_TYPES.BADGE_EARNED]: "low",
  [NOTIFICATION_TYPES.NEW_MESSAGE]: "medium",
  [NOTIFICATION_TYPES.PHYSIQUE_LIKED]: "low",
  [NOTIFICATION_TYPES.PHYSIQUE_COMMENTED]: "low",
  [NOTIFICATION_TYPES.PHYSIQUE_REACTED]: "low",
};

const TYPE_CONFIDENCE = {
  [NOTIFICATION_TYPES.MUSCLE_GROUP_NEGLECTED]: "medium",
  [NOTIFICATION_TYPES.PERSONAL_RECORD]: "high",
  [NOTIFICATION_TYPES.HIGHEST_VOLUME]: "high",
  [NOTIFICATION_TYPES.LONGEST_WORKOUT]: "high",
  [NOTIFICATION_TYPES.NEW_LONGEST_RUN]: "high",
  [NOTIFICATION_TYPES.FIRST_WORKOUT_AFTER_BREAK]: "high",
  [NOTIFICATION_TYPES.WEEKLY_VOLUME_INCREASED]: "high",
  [NOTIFICATION_TYPES.GOAL_COMPLETED]: "high",
  [NOTIFICATION_TYPES.GOAL_THRESHOLD]: "high",
  [NOTIFICATION_TYPES.GOAL_PROGRESS_REMINDER]: "high",
  [NOTIFICATION_TYPES.GOAL_EXPIRING_TODAY]: "high",
  [NOTIFICATION_TYPES.MILESTONE_ALMOST_COMPLETE]: "high",
  [NOTIFICATION_TYPES.STREAK_MILESTONE]: "high",
  [NOTIFICATION_TYPES.STREAK_PROTECTION]: "high",
  [NOTIFICATION_TYPES.CARDIO_STREAK_EXPIRING]: "high",
  [NOTIFICATION_TYPES.WORKOUT_TODAY]: "high",
  [NOTIFICATION_TYPES.WORKOUT_STARTING_SOON]: "high",
  [NOTIFICATION_TYPES.WORKOUT_OVERDUE]: "high",
  [NOTIFICATION_TYPES.WORKOUT_MISSED_YESTERDAY]: "high",
  [NOTIFICATION_TYPES.RECURRING_DUE_TOMORROW]: "high",

  [NOTIFICATION_TYPES.CARDIO_SESSION_DUE]: "medium",
  [NOTIFICATION_TYPES.CARDIO_ACTIVITY_NOT_LOGGED]: "medium",

  [NOTIFICATION_TYPES.PLANNER_RESCHEDULE_WARNING]: "low",
  [NOTIFICATION_TYPES.PLANNER_OVERLAP]: "low",
  [NOTIFICATION_TYPES.PLANNER_SERIES_ENDING_SOON]: "low",
  [NOTIFICATION_TYPES.WORKOUT_SCHEDULED]: "low",
  [NOTIFICATION_TYPES.WORKOUT_RESCHEDULED]: "low",
  [NOTIFICATION_TYPES.RECURRING_SCHEDULE_CREATED]: "low",
  [NOTIFICATION_TYPES.WORKOUT_CANCELLED]: "low",

  [NOTIFICATION_TYPES.PLATEAU_DETECTED]: "medium",
  [NOTIFICATION_TYPES.WEEKLY_GRADE_IMPROVED]: "high",
  [NOTIFICATION_TYPES.VOLUME_LANDMARK_ACHIEVED]: "medium",

  [NOTIFICATION_TYPES.NEW_FOLLOWER]: "high",
  [NOTIFICATION_TYPES.BADGE_EARNED]: "high",
  [NOTIFICATION_TYPES.NEW_MESSAGE]: "high",
  [NOTIFICATION_TYPES.PHYSIQUE_LIKED]: "high",
  [NOTIFICATION_TYPES.PHYSIQUE_COMMENTED]: "high",
  [NOTIFICATION_TYPES.PHYSIQUE_REACTED]: "high",
};

const STREAK_MILESTONES = [7, 14, 30, 60, 100];

const GOAL_PROGRESS_THRESHOLDS = [80, 90];

module.exports = {
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_TYPES,
  TYPE_PRIORITY,
  TYPE_CONFIDENCE,
  STREAK_MILESTONES,
  GOAL_PROGRESS_THRESHOLDS,
};
